version: '3.8'

services:
  mysql-0:
    image: mysql:8.0
    container_name: mysql-0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data1:/var/lib/mysql

  mysql-1:
    image: mysql:8.0
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: post2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data2:/var/lib/mysql

  mysql-2:
    image: mysql:8.0
    container_name: mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: post3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data3:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  mysql-data1:
  mysql-data2:
  mysql-data3: